### ISSUE TITLE
Incompatible with GPGS (Unity)

### ISSUE THREAD

**Issue by hippogamesunity** [Flymob/Unity-Plugin#2]
Please add instructions how to integrate your plugin to be compatible with the latest version of Google Play Game Services plugin for Unity.

**Comment by hippogamesunity** [comment]
I've got conflicts with the following libs (I have to delete them all):
FlyMobSdk/libs/android-support-v4.jar
FlyMobSdk/libs/play-services-ads-8.4.0.jar (so I think AdMob will not work)
FlyMobSdk/libs/play-services-basement-8.4.0.jar
FlyMobSdk/libs/vungle-dagger-2.4.jar (which doesn't exist in clean Vungle setup)
FlyMobSdk/libs/vungle-publisher-adaptive-id-4.0.2.jar (which doesn't exist in clean Vungle setup)

**Comment by trimf** [comment]
If you have conflicts, you should remove libs either from our plugin or from other plugin.

**Comment by hippogamesunity** [comment]
What about play-services-ads-8.4.0.jar? I can't detect conflicting lib, but I have no another play-services-ads lib in my project.
