### ISSUE TITLE
Too many field references

### ISSUE THREAD

**Issue by hippogamesunity** [Flymob/Unity-Plugin#3]
Got this error after resolving all plugin conflicts:
CommandInvokationFailure: Unable to convert classes into dex format.
trouble writing output: Too many field references: 65679; max is 65536.

I know this issue relates to Unity more (https://habrahabr.ru/post/314416/).
Here is my plugin list:
- AppMetrica
- Amplitude
- Facebook SDK
- Tune
- Chartboost
- GPGS
- FlyMob

**Comment by trimf** [comment]
Habrahabr contains the answer.
1. You can export project and resolve multidex in it.
2. You can remove unnecessary jars in unity.
